const list = [
  {
    id: 1,
    title: "EYEBOGLER",
    color: "Black",
    size: "L",
    price: 499,
    img: "https://m.media-amazon.com/images/I/51ZIqCyzpbL._AC_UL480_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "More & More",
    color: "Multi",
    size: "L",
    price: 499,
    img: "https://m.media-amazon.com/images/I/6113wVBRBoL._AC_UL480_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "BAGHADBILLO",
    color: "Black",
    size: "XL",
    price: 799,
    img: "https://m.media-amazon.com/images/I/71fNC29PcqL._AC_UL480_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "JERKYN",
    color: "Grey",
    size: "M",
    price: 499,
    img: "https://m.media-amazon.com/images/I/41vABBIr6ZL._AC_UL480_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "Trillion",
    color: "Grey",
    size: "S",
    price: 599,
    img: "https://m.media-amazon.com/images/I/51Hz7KZL2TL._AC_UL480_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "ADRO",
    color: "Black",
    size: "M",
    price: 299,
    img: "https://m.media-amazon.com/images/I/51W0YDiJobL._AC_UL480_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "ADRO ",
    color: "olive Green",
    size: "L",
    price: 399,
    img: "https://m.media-amazon.com/images/I/61EAQ1Xh0+L._AC_UL480_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "TeeBustrr",
    color: "Black",
    size: "XL",
    price: 599,
    img: "https://m.media-amazon.com/images/I/61miZKc6vjL._AC_UL480_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "ABSOLUTE DEFENSE",
    color: "Carbon red",
    size: "L",
    price: 499,
    img: "https://m.media-amazon.com/images/I/61L903jSl5L._AC_UL480_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "More & More",
    color: "Black",
    size: "L",
    price: 499,
    img: "https://m.media-amazon.com/images/I/61U2Wu4Z2NL._AC_UL480_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "TeeBustrr",
    color: "Black",
    size: "L",
    price: 1999,
    img: "https://m.media-amazon.com/images/I/61JkM8IwL4L._AC_UL480_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "The Modern Soul",
    color: "Grey",
    size: "M",
    price: 999,
    img: "https://m.media-amazon.com/images/I/51AiUV++wIL._AC_UL480_FMwebp_QL65_.jpg",
    amount: 1,
  },
];

export default list;
